---
title: "hbgd"
subtitle: "healthy birth, growth & development"
author: Ryan Hafen
output:
  packagedocs:
    toc: true
navpills: |
  <li><a href='index.html'>Docs</a></li>
  <li class="active"><a href='rd.html'>Package Ref</a></li>
---
<h1>Healthy birth, growth &amp; development</h1>

<p><strong>Authors:</strong> <a href="mailto:rhafen@gmail.com">Ryan Hafen</a> [aut, cre]</p>
<p><strong>Version:</strong> 0.2</p>
<p><strong>License:</strong> MIT + file LICENSE</p>

<h4>Description</h4>
<p>A package for visual and analytical methods for the analysis of
longitudinal growth data.</p>

<h4>Depends</h4>
<p>
R (>= 3.1),
datadr,
trelliscope</p>

<h4>Imports</h4>
<p>
dplyr,
lattice,
rbokeh (>= 0.2.4.1),
ggplot2,
mgcv,
MASS,
numDeriv,
gamlss.dist</p>

<h4>Suggests</h4>
<p>
testthat</p>

<h4>Enhances</h4>
<p>(none)</p>

# WHO Growth Standards



## who_wtkg2zscore

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_htcm2zscore

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_bmi2zscore

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_hcircm2zscore

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_muaccm2zscore

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_ss2zscore

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_tsftmm2zscore

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_wtkg2centile

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_htcm2centile

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_bmi2centile

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_hcircm2centile

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_muaccm2centile

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_ss2centile

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_tsftmm2centile

<h3>Convert anthro measurements to WHO z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agedays</dt>
  <dd class="rd-dd">age in days</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>htcm</dt>
  <dd class="rd-dd">height(cm) measurement(s) to convert</dd>
  <dt>bmi</dt>
  <dd class="rd-dd">body-mass index measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>muaccm</dt>
  <dd class="rd-dd">mid-upper arm circumference (cm) measurement(s) to convert</dd>
  <dt>ss</dt>
  <dd class="rd-dd">subscalpular skinfold (cm) measurement(s) to convert</dd>
  <dt>tsftmm</dt>
  <dd class="rd-dd">triceps skinfold (mm) measurement(s) to convert</dd>
</dl>





## who_value2zscore

<h3>Convert anthro measurements to WHO z-scores/centiles (generic)</h3>

<p class="rd-p">Compute z-scores or centiles with respect to the WHO growth standard for given values of x vs. y (typically x is "agedays" and y is a measure like "htcm").</p>

<h4>Usage</h4>
<pre class="r"><code>who_value2zscore(x, y, x_var = "agedays", y_var = "htcm", sex = "Female",
  data = NULL)

who_value2centile(x, y, x_var = "agedays", y_var = "htcm", sex = "Female")</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>y</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>y_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays") - see details</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg") - see details</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>data</dt>
  <dd class="rd-dd">optional data frame that supplies any of the other variables provided to the function</dd>
</dl>

  <h4>Details</h4>

  <p class="rd-p">for all supported pairings of <code>x_var</code> and <code>y_var</code>, type <code>names(who)</code></p>



<h4>Examples</h4>
<pre class="r"><code># z-scores
who_value2zscore(1670, in2cm(44))
who_value2zscore(1670, lb2kg(48), y_var = "wtkg")

who_value2centile(1670, in2cm(44))
who_value2centile(1670, lb2kg(48), y_var = "wtkg")

# add haz derived from WHO data and compare to that provided with data
cpp$haz2 <- who_value2zscore(x = agedays,  y = lencm, sex = sex, data = cpp)
plot(cpp$haz, cpp$haz2)

# note that you can also do it this way
#' cpp$haz2 <- who_value2zscore(cpp$agedays, cpp$lencm, sex = cpp$sex)</code></pre>

<h4>See also</h4>

<code><a href=#who_centile2value>who_centile2value</a></code>, <code><a href=#who_centile2value>who_zscore2value</a></code>




## who_zscore2value

<h3>Convert WHO z-scores/centiles to anthro measurements (generic)</h3>

<p class="rd-p">Get values of a specified measurement for a given WHO centile/z-score and growth standard pair (e.g. length vs. age) and sex over a specified grid</p>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">vector specifying the values of x over which to provide the centiles for y</dd>
  <dt>p</dt>
  <dd class="rd-dd">centile or vector of centiles at which to compute values (a number between 0 and 100 - 50 is median)</dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays") - see details</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg") that specifies which variable of values should be returned for the specified value of q - see details</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>data</dt>
  <dd class="rd-dd">optional data frame that supplies any of the other variables provided to the function</dd>
  <dt>z</dt>
  <dd class="rd-dd">z-score or vector of z-scores at which to compute values</dd>
</dl>

  <h4>Details</h4>

  <p class="rd-p">for all supported pairings of <code>x_var</code> and <code>y_var</code>, type <code>names(who)</code></p>




<h4>See also</h4>

<code><a href=#who_value2zscore>who_value2centile</a></code>, <code><a href=#who_value2zscore>who_value2zscore</a></code>




## who_value2centile

<h3>Convert anthro measurements to WHO z-scores/centiles (generic)</h3>

<p class="rd-p">Compute z-scores or centiles with respect to the WHO growth standard for given values of x vs. y (typically x is "agedays" and y is a measure like "htcm").</p>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>y</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>y_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays") - see details</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg") - see details</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>data</dt>
  <dd class="rd-dd">optional data frame that supplies any of the other variables provided to the function</dd>
</dl>

  <h4>Details</h4>

  <p class="rd-p">for all supported pairings of <code>x_var</code> and <code>y_var</code>, type <code>names(who)</code></p>




<h4>See also</h4>

<code><a href=#who_centile2value>who_centile2value</a></code>, <code><a href=#who_centile2value>who_zscore2value</a></code>




## who_centile2value

<h3>Convert WHO z-scores/centiles to anthro measurements (generic)</h3>

<p class="rd-p">Get values of a specified measurement for a given WHO centile/z-score and growth standard pair (e.g. length vs. age) and sex over a specified grid</p>

<h4>Usage</h4>
<pre class="r"><code>who_centile2value(x, p = 50, x_var = "agedays", y_var = "htcm",
  sex = "Female", data = NULL)

who_zscore2value(x, z = 0, y_var = "htcm", x_var = "agedays",
  sex = "Female", data = NULL)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">vector specifying the values of x over which to provide the centiles for y</dd>
  <dt>p</dt>
  <dd class="rd-dd">centile or vector of centiles at which to compute values (a number between 0 and 100 - 50 is median)</dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays") - see details</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg") that specifies which variable of values should be returned for the specified value of q - see details</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>data</dt>
  <dd class="rd-dd">optional data frame that supplies any of the other variables provided to the function</dd>
  <dt>z</dt>
  <dd class="rd-dd">z-score or vector of z-scores at which to compute values</dd>
</dl>

  <h4>Details</h4>

  <p class="rd-p">for all supported pairings of <code>x_var</code> and <code>y_var</code>, type <code>names(who)</code></p>



<h4>Examples</h4>
<pre class="r"><code># median height vs. age for females
x <- seq(0, 365, by = 7)
med <- who_centile2value(x)
plot(x, med, xlab = "age in days", ylab = "median female height (cm)")

# 99th percentile of weight vs. age for males from age 0 to 1461 days
dat <- data.frame(x = rep(seq(0, 1461, length = 100), 2),
  sex = rep(c("Male", "Female"), each = 100))
dat$p99 <- who_centile2value(x, p = 99, y_var = "wtkg", sex = sex, data = dat)
lattice::xyplot(kg2lb(p99) ~ days2years(x), groups = sex, data = dat,
  ylab = "99th percentile weight (pounds) for males",
  xlab = "age (years)", auto.key = TRUE)</code></pre>

<h4>See also</h4>

<code><a href=#who_value2zscore>who_value2centile</a></code>, <code><a href=#who_value2zscore>who_value2zscore</a></code>


# Intergrowth Birth Standards



## igb_lencm2zscore

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days</dd>
  <dt>lencm</dt>
  <dd class="rd-dd">length(cm) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>






## igb_wtkg2zscore

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days</dd>
  <dt>lencm</dt>
  <dd class="rd-dd">length(cm) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>






## igb_hcircm2zscore

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days</dd>
  <dt>lencm</dt>
  <dd class="rd-dd">length(cm) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>






## igb_lencm2centile

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days</dd>
  <dt>lencm</dt>
  <dd class="rd-dd">length(cm) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>






## igb_wtkg2centile

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days</dd>
  <dt>lencm</dt>
  <dd class="rd-dd">length(cm) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>






## igb_hcircm2centile

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days</dd>
  <dt>lencm</dt>
  <dd class="rd-dd">length(cm) measurement(s) to convert</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>wtkg</dt>
  <dd class="rd-dd">weight (kg) measurement(s) to convert</dd>
  <dt>hcircm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>






## igb_value2zscore

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles (generic)</h3>


<h4>Usage</h4>
<pre class="r"><code>igb_value2centile(gagebrth, val, var = "lencm", sex = "Female")

igb_value2zscore(gagebrth, val, var = "lencm", sex = "Female")</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days</dd>
  <dt>val</dt>
  <dd class="rd-dd">the value(s) of the anthro measurement to convert</dd>
  <dt>var</dt>
  <dd class="rd-dd">the name of the measurement to convert ("lencm", "wtkg", "hcircm")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>



<h4>Examples</h4>
<pre class="r"><code># get Male birth length z-scores
# first we need just 1 record per subject with subject-level data
cppsubj <- get_subject_data(cpp)
cppsubj <- subset(cppsubj, sex == "Male")
igb_value2zscore(cpp$gagebrth, cpp$birthlen, var = "lencm", sex = "Male")</code></pre>



## igb_zscore2value

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles (generic)</h3>


<h4>Usage</h4>
<pre class="r"><code>igb_centile2value(gagebrth, p = 50, var = "lencm", sex = "Female")

igb_zscore2value(gagebrth, z = 0, var = "lencm", sex = "Female")</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days</dd>
  <dt>p</dt>
  <dd class="rd-dd">centile(s) to convert (must be between 0 and 100)</dd>
  <dt>var</dt>
  <dd class="rd-dd">the name of the measurement to convert ("lencm", "wtkg", "hcircm")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>z</dt>
  <dd class="rd-dd">z-score(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>



<h4>Examples</h4>
<pre class="r"><code># get 99th centile for Male birth weights across some gestational ages
igb_centile2value(232:300, 99, var = "wtkg", sex = "Male")</code></pre>



## igb_value2centile

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles (generic)</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days</dd>
  <dt>val</dt>
  <dd class="rd-dd">the value(s) of the anthro measurement to convert</dd>
  <dt>var</dt>
  <dd class="rd-dd">the name of the measurement to convert ("lencm", "wtkg", "hcircm")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>






## igb_centile2value

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles (generic)</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days</dd>
  <dt>p</dt>
  <dd class="rd-dd">centile(s) to convert (must be between 0 and 100)</dd>
  <dt>var</dt>
  <dd class="rd-dd">the name of the measurement to convert ("lencm", "wtkg", "hcircm")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>z</dt>
  <dd class="rd-dd">z-score(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>




# Intergrowth Prenatal Standards



## igpre_hccm2zscore

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>hccm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>bpdcm</dt>
  <dd class="rd-dd">biparietel diameter (cm) measurement(s) to convert</dd>
  <dt>ofdcm</dt>
  <dd class="rd-dd">occipito-frontal diameter (cm) measurement(s) to convert</dd>
  <dt>accm</dt>
  <dd class="rd-dd">abdominal circumference (cm) measurement(s) to convert</dd>
  <dt>flcm</dt>
  <dd class="rd-dd">femur length (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_bpdcm2zscore

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>hccm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>bpdcm</dt>
  <dd class="rd-dd">biparietel diameter (cm) measurement(s) to convert</dd>
  <dt>ofdcm</dt>
  <dd class="rd-dd">occipito-frontal diameter (cm) measurement(s) to convert</dd>
  <dt>accm</dt>
  <dd class="rd-dd">abdominal circumference (cm) measurement(s) to convert</dd>
  <dt>flcm</dt>
  <dd class="rd-dd">femur length (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_ofdcm2zscore

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>hccm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>bpdcm</dt>
  <dd class="rd-dd">biparietel diameter (cm) measurement(s) to convert</dd>
  <dt>ofdcm</dt>
  <dd class="rd-dd">occipito-frontal diameter (cm) measurement(s) to convert</dd>
  <dt>accm</dt>
  <dd class="rd-dd">abdominal circumference (cm) measurement(s) to convert</dd>
  <dt>flcm</dt>
  <dd class="rd-dd">femur length (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_accm2zscore

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>hccm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>bpdcm</dt>
  <dd class="rd-dd">biparietel diameter (cm) measurement(s) to convert</dd>
  <dt>ofdcm</dt>
  <dd class="rd-dd">occipito-frontal diameter (cm) measurement(s) to convert</dd>
  <dt>accm</dt>
  <dd class="rd-dd">abdominal circumference (cm) measurement(s) to convert</dd>
  <dt>flcm</dt>
  <dd class="rd-dd">femur length (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_flcm2zscore

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>hccm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>bpdcm</dt>
  <dd class="rd-dd">biparietel diameter (cm) measurement(s) to convert</dd>
  <dt>ofdcm</dt>
  <dd class="rd-dd">occipito-frontal diameter (cm) measurement(s) to convert</dd>
  <dt>accm</dt>
  <dd class="rd-dd">abdominal circumference (cm) measurement(s) to convert</dd>
  <dt>flcm</dt>
  <dd class="rd-dd">femur length (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_hccm2centile

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>hccm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>bpdcm</dt>
  <dd class="rd-dd">biparietel diameter (cm) measurement(s) to convert</dd>
  <dt>ofdcm</dt>
  <dd class="rd-dd">occipito-frontal diameter (cm) measurement(s) to convert</dd>
  <dt>accm</dt>
  <dd class="rd-dd">abdominal circumference (cm) measurement(s) to convert</dd>
  <dt>flcm</dt>
  <dd class="rd-dd">femur length (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_bpdcm2centile

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>hccm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>bpdcm</dt>
  <dd class="rd-dd">biparietel diameter (cm) measurement(s) to convert</dd>
  <dt>ofdcm</dt>
  <dd class="rd-dd">occipito-frontal diameter (cm) measurement(s) to convert</dd>
  <dt>accm</dt>
  <dd class="rd-dd">abdominal circumference (cm) measurement(s) to convert</dd>
  <dt>flcm</dt>
  <dd class="rd-dd">femur length (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_ofdcm2centile

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>hccm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>bpdcm</dt>
  <dd class="rd-dd">biparietel diameter (cm) measurement(s) to convert</dd>
  <dt>ofdcm</dt>
  <dd class="rd-dd">occipito-frontal diameter (cm) measurement(s) to convert</dd>
  <dt>accm</dt>
  <dd class="rd-dd">abdominal circumference (cm) measurement(s) to convert</dd>
  <dt>flcm</dt>
  <dd class="rd-dd">femur length (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_accm2centile

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>hccm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>bpdcm</dt>
  <dd class="rd-dd">biparietel diameter (cm) measurement(s) to convert</dd>
  <dt>ofdcm</dt>
  <dd class="rd-dd">occipito-frontal diameter (cm) measurement(s) to convert</dd>
  <dt>accm</dt>
  <dd class="rd-dd">abdominal circumference (cm) measurement(s) to convert</dd>
  <dt>flcm</dt>
  <dd class="rd-dd">femur length (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_flcm2centile

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>hccm</dt>
  <dd class="rd-dd">head circumference (cm) measurement(s) to convert</dd>
  <dt>bpdcm</dt>
  <dd class="rd-dd">biparietel diameter (cm) measurement(s) to convert</dd>
  <dt>ofdcm</dt>
  <dd class="rd-dd">occipito-frontal diameter (cm) measurement(s) to convert</dd>
  <dt>accm</dt>
  <dd class="rd-dd">abdominal circumference (cm) measurement(s) to convert</dd>
  <dt>flcm</dt>
  <dd class="rd-dd">femur length (cm) measurement(s) to convert</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_value2zscore

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles (generic)</h3>


<h4>Usage</h4>
<pre class="r"><code>igpre_value2zscore(gagedays, val, var = c("hccm", "bpdcm", "ofdcm", "accm",
  "flcm"))

igpre_value2centile(gagedays, val, var = c("hccm", "bpdcm", "ofdcm", "accm",
  "flcm"))</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>val</dt>
  <dd class="rd-dd">the value(s) of the anthro measurement to convert</dd>
  <dt>var</dt>
  <dd class="rd-dd">the name of the measurement to convert ("hccm", "bpdcm", "ofdcm", "accm", "flcm")</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>



<h4>Examples</h4>
<pre class="r"><code># get centile for child at 100 gestational days with 11 cm head circumference
igpre_hccm2centile(100, 11)</code></pre>



## igpre_zscore2value

<h3>Convert Intergrowth z-scores/centiles to prenatal ultrasound measurements (generic)</h3>


<h4>Usage</h4>
<pre class="r"><code>igpre_zscore2value(gagedays, z = 0, var = c("hccm", "bpdcm", "ofdcm",
  "accm", "flcm"))

igpre_centile2value(gagedays, p = 50, var = c("hccm", "bpdcm", "ofdcm",
  "accm", "flcm"))</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>z</dt>
  <dd class="rd-dd">z-score(s) to convert</dd>
  <dt>var</dt>
  <dd class="rd-dd">the name of the measurement to convert ("hccm", "bpdcm", "ofdcm", "accm", "flcm")</dd>
  <dt>p</dt>
  <dd class="rd-dd">centile(s) to convert (must be between 0 and 100)</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>



<h4>Examples</h4>
<pre class="r"><code># get value for median head circumference for child at 100 gestational days
igpre_centile2value(100, 50, var = "hccm")</code></pre>



## igpre_value2centile

<h3>Convert prenatal ultrasound measurements to Intergrowth z-scores/centiles (generic)</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>val</dt>
  <dd class="rd-dd">the value(s) of the anthro measurement to convert</dd>
  <dt>var</dt>
  <dd class="rd-dd">the name of the measurement to convert ("hccm", "bpdcm", "ofdcm", "accm", "flcm")</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>






## igpre_centile2value

<h3>Convert Intergrowth z-scores/centiles to prenatal ultrasound measurements (generic)</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days</dd>
  <dt>z</dt>
  <dd class="rd-dd">z-score(s) to convert</dd>
  <dt>var</dt>
  <dd class="rd-dd">the name of the measurement to convert ("hccm", "bpdcm", "ofdcm", "accm", "flcm")</dd>
  <dt>p</dt>
  <dd class="rd-dd">centile(s) to convert (must be between 0 and 100)</dd>
</dl>

  <h4>References</h4>

  <p class="rd-p">International standards for fetal growth based on serial ultrasound measurements: the Fetal Growth Longitudinal Study of the INTERGROWTH-21st Project
Papageorghiou, Aris T et al.
The Lancet, Volume 384, Issue 9946, 869-879</p>




# Growth Standard Vis



## ly_who

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays")</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>p</dt>
  <dd class="rd-dd">centiles at which to draw the growth standard band polygons (only need to specify on one side of the median)</dd>
  <dt>color</dt>
  <dd class="rd-dd">optional color to use for bands (will use <code>sex</code> to determine if not specified)</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>center</dt>
  <dd class="rd-dd">should the bands be centered around the median?</dd>
  <dt>labels</dt>
  <dd class="rd-dd">should the centiles be labeled? (not implemented)</dd>
  <dt>x_trans</dt>
  <dd class="rd-dd">transformation function to be applied to x-axis</dd>
  <dt>y_trans</dt>
  <dd class="rd-dd">transformation function to be applied to y-axis</dd>
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days (for igb plots)</dd>
  <dt>var</dt>
  <dd class="rd-dd">variable name for y axis for igb or igpre plots ("lencm", "wtkg", or "hcircm" for igb; "accm", "bpdcm", "flcm", "hccm", or "ofdcm" for igpre)</dd>
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days (for igpre plots)</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add growth standard to</dd>
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add growth standard to</dd>
</dl>





## ly_igb

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays")</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>p</dt>
  <dd class="rd-dd">centiles at which to draw the growth standard band polygons (only need to specify on one side of the median)</dd>
  <dt>color</dt>
  <dd class="rd-dd">optional color to use for bands (will use <code>sex</code> to determine if not specified)</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>center</dt>
  <dd class="rd-dd">should the bands be centered around the median?</dd>
  <dt>labels</dt>
  <dd class="rd-dd">should the centiles be labeled? (not implemented)</dd>
  <dt>x_trans</dt>
  <dd class="rd-dd">transformation function to be applied to x-axis</dd>
  <dt>y_trans</dt>
  <dd class="rd-dd">transformation function to be applied to y-axis</dd>
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days (for igb plots)</dd>
  <dt>var</dt>
  <dd class="rd-dd">variable name for y axis for igb or igpre plots ("lencm", "wtkg", or "hcircm" for igb; "accm", "bpdcm", "flcm", "hccm", or "ofdcm" for igpre)</dd>
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days (for igpre plots)</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add growth standard to</dd>
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add growth standard to</dd>
</dl>





## ly_igpre

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays")</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>p</dt>
  <dd class="rd-dd">centiles at which to draw the growth standard band polygons (only need to specify on one side of the median)</dd>
  <dt>color</dt>
  <dd class="rd-dd">optional color to use for bands (will use <code>sex</code> to determine if not specified)</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>center</dt>
  <dd class="rd-dd">should the bands be centered around the median?</dd>
  <dt>labels</dt>
  <dd class="rd-dd">should the centiles be labeled? (not implemented)</dd>
  <dt>x_trans</dt>
  <dd class="rd-dd">transformation function to be applied to x-axis</dd>
  <dt>y_trans</dt>
  <dd class="rd-dd">transformation function to be applied to y-axis</dd>
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days (for igb plots)</dd>
  <dt>var</dt>
  <dd class="rd-dd">variable name for y axis for igb or igpre plots ("lencm", "wtkg", or "hcircm" for igb; "accm", "bpdcm", "flcm", "hccm", or "ofdcm" for igpre)</dd>
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days (for igpre plots)</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add growth standard to</dd>
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add growth standard to</dd>
</dl>





## ly_zband

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add z bands to</dd>
  <dt>x</dt>
  <dd class="rd-dd">range on x axis that should be covered by bands</dd>
  <dt>z</dt>
  <dd class="rd-dd">z-scores at which to draw bands (only need to specify on one side of zero)</dd>
  <dt>color</dt>
  <dd class="rd-dd">color to use for bands</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add z bands to</dd>
</dl>





## panel.who

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays")</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>p</dt>
  <dd class="rd-dd">centiles at which to draw the growth standard band polygons (only need to specify on one side of the median)</dd>
  <dt>color</dt>
  <dd class="rd-dd">optional color to use for bands (will use <code>sex</code> to determine if not specified)</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>center</dt>
  <dd class="rd-dd">should the bands be centered around the median?</dd>
  <dt>labels</dt>
  <dd class="rd-dd">should the centiles be labeled? (not implemented)</dd>
  <dt>x_trans</dt>
  <dd class="rd-dd">transformation function to be applied to x-axis</dd>
  <dt>y_trans</dt>
  <dd class="rd-dd">transformation function to be applied to y-axis</dd>
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days (for igb plots)</dd>
  <dt>var</dt>
  <dd class="rd-dd">variable name for y axis for igb or igpre plots ("lencm", "wtkg", or "hcircm" for igb; "accm", "bpdcm", "flcm", "hccm", or "ofdcm" for igpre)</dd>
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days (for igpre plots)</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add growth standard to</dd>
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add growth standard to</dd>
</dl>





## panel.igb

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays")</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>p</dt>
  <dd class="rd-dd">centiles at which to draw the growth standard band polygons (only need to specify on one side of the median)</dd>
  <dt>color</dt>
  <dd class="rd-dd">optional color to use for bands (will use <code>sex</code> to determine if not specified)</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>center</dt>
  <dd class="rd-dd">should the bands be centered around the median?</dd>
  <dt>labels</dt>
  <dd class="rd-dd">should the centiles be labeled? (not implemented)</dd>
  <dt>x_trans</dt>
  <dd class="rd-dd">transformation function to be applied to x-axis</dd>
  <dt>y_trans</dt>
  <dd class="rd-dd">transformation function to be applied to y-axis</dd>
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days (for igb plots)</dd>
  <dt>var</dt>
  <dd class="rd-dd">variable name for y axis for igb or igpre plots ("lencm", "wtkg", or "hcircm" for igb; "accm", "bpdcm", "flcm", "hccm", or "ofdcm" for igpre)</dd>
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days (for igpre plots)</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add growth standard to</dd>
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add growth standard to</dd>
</dl>





## panel.igpre

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays")</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>p</dt>
  <dd class="rd-dd">centiles at which to draw the growth standard band polygons (only need to specify on one side of the median)</dd>
  <dt>color</dt>
  <dd class="rd-dd">optional color to use for bands (will use <code>sex</code> to determine if not specified)</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>center</dt>
  <dd class="rd-dd">should the bands be centered around the median?</dd>
  <dt>labels</dt>
  <dd class="rd-dd">should the centiles be labeled? (not implemented)</dd>
  <dt>x_trans</dt>
  <dd class="rd-dd">transformation function to be applied to x-axis</dd>
  <dt>y_trans</dt>
  <dd class="rd-dd">transformation function to be applied to y-axis</dd>
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days (for igb plots)</dd>
  <dt>var</dt>
  <dd class="rd-dd">variable name for y axis for igb or igpre plots ("lencm", "wtkg", or "hcircm" for igb; "accm", "bpdcm", "flcm", "hccm", or "ofdcm" for igpre)</dd>
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days (for igpre plots)</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add growth standard to</dd>
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add growth standard to</dd>
</dl>





## panel.zband

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add z bands to</dd>
  <dt>x</dt>
  <dd class="rd-dd">range on x axis that should be covered by bands</dd>
  <dt>z</dt>
  <dd class="rd-dd">z-scores at which to draw bands (only need to specify on one side of zero)</dd>
  <dt>color</dt>
  <dd class="rd-dd">color to use for bands</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add z bands to</dd>
</dl>





## geom_who

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays")</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>p</dt>
  <dd class="rd-dd">centiles at which to draw the growth standard band polygons (only need to specify on one side of the median)</dd>
  <dt>color</dt>
  <dd class="rd-dd">optional color to use for bands (will use <code>sex</code> to determine if not specified)</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>center</dt>
  <dd class="rd-dd">should the bands be centered around the median?</dd>
  <dt>labels</dt>
  <dd class="rd-dd">should the centiles be labeled? (not implemented)</dd>
  <dt>x_trans</dt>
  <dd class="rd-dd">transformation function to be applied to x-axis</dd>
  <dt>y_trans</dt>
  <dd class="rd-dd">transformation function to be applied to y-axis</dd>
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days (for igb plots)</dd>
  <dt>var</dt>
  <dd class="rd-dd">variable name for y axis for igb or igpre plots ("lencm", "wtkg", or "hcircm" for igb; "accm", "bpdcm", "flcm", "hccm", or "ofdcm" for igpre)</dd>
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days (for igpre plots)</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add growth standard to</dd>
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add growth standard to</dd>
</dl>





## geom_igb

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays")</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>p</dt>
  <dd class="rd-dd">centiles at which to draw the growth standard band polygons (only need to specify on one side of the median)</dd>
  <dt>color</dt>
  <dd class="rd-dd">optional color to use for bands (will use <code>sex</code> to determine if not specified)</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>center</dt>
  <dd class="rd-dd">should the bands be centered around the median?</dd>
  <dt>labels</dt>
  <dd class="rd-dd">should the centiles be labeled? (not implemented)</dd>
  <dt>x_trans</dt>
  <dd class="rd-dd">transformation function to be applied to x-axis</dd>
  <dt>y_trans</dt>
  <dd class="rd-dd">transformation function to be applied to y-axis</dd>
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days (for igb plots)</dd>
  <dt>var</dt>
  <dd class="rd-dd">variable name for y axis for igb or igpre plots ("lencm", "wtkg", or "hcircm" for igb; "accm", "bpdcm", "flcm", "hccm", or "ofdcm" for igpre)</dd>
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days (for igpre plots)</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add growth standard to</dd>
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add growth standard to</dd>
</dl>





## geom_igpre

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value or vector of values that correspond to a measure defined by <code>x_var</code></dd>
  <dt>x_var</dt>
  <dd class="rd-dd">x variable name (typically "agedays")</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">y variable name (typically "htcm" or "wtkg")</dd>
  <dt>sex</dt>
  <dd class="rd-dd">"Male" or "Female"</dd>
  <dt>p</dt>
  <dd class="rd-dd">centiles at which to draw the growth standard band polygons (only need to specify on one side of the median)</dd>
  <dt>color</dt>
  <dd class="rd-dd">optional color to use for bands (will use <code>sex</code> to determine if not specified)</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>center</dt>
  <dd class="rd-dd">should the bands be centered around the median?</dd>
  <dt>labels</dt>
  <dd class="rd-dd">should the centiles be labeled? (not implemented)</dd>
  <dt>x_trans</dt>
  <dd class="rd-dd">transformation function to be applied to x-axis</dd>
  <dt>y_trans</dt>
  <dd class="rd-dd">transformation function to be applied to y-axis</dd>
  <dt>gagebrth</dt>
  <dd class="rd-dd">gestational age at birth in days (for igb plots)</dd>
  <dt>var</dt>
  <dd class="rd-dd">variable name for y axis for igb or igpre plots ("lencm", "wtkg", or "hcircm" for igb; "accm", "bpdcm", "flcm", "hccm", or "ofdcm" for igpre)</dd>
  <dt>gagedays</dt>
  <dd class="rd-dd">gestational age in days (for igpre plots)</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add growth standard to</dd>
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add growth standard to</dd>
</dl>





## geom_zband

<h3>Utility functions for adding growth standard bands to rbokeh/lattice/ggplot2 plots</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>fig</dt>
  <dd class="rd-dd">rbokeh figure to add z bands to</dd>
  <dt>x</dt>
  <dd class="rd-dd">range on x axis that should be covered by bands</dd>
  <dt>z</dt>
  <dd class="rd-dd">z-scores at which to draw bands (only need to specify on one side of zero)</dd>
  <dt>color</dt>
  <dd class="rd-dd">color to use for bands</dd>
  <dt>alpha</dt>
  <dd class="rd-dd">transparency of the bands</dd>
  <dt>obj</dt>
  <dd class="rd-dd">ggplot2 object to add z bands to</dd>
</dl>



# Modeling



## fit_trajectory

<h3>Fit a model to an individual's trajectory and optionally add checkpoints</h3>


<h4>Usage</h4>
<pre class="r"><code>fit_trajectory(dat, x_var = "agedays", y_var = "htcm", method = "gam",
  xg = NULL, checkpoints = 365 * c(1:2), z_bins = c(-2, 2),
  x_trans = NULL, x_inv = NULL, y_trans = NULL, y_inv = NULL, ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data frame containing variables to model</dd>
  <dt>x_var</dt>
  <dd class="rd-dd">name of x variable to model</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">name of y variable to model</dd>
  <dt>method</dt>
  <dd class="rd-dd">one of "gam", "loess", "fda", "rlm"</dd>
  <dt>xg</dt>
  <dd class="rd-dd">grid of x points at which the fit should be evaluated for plotting (if <code>NULL</code> it will be set to an equally-spaced grid of 150 points across <code>x</code>)</dd>
  <dt>checkpoints</dt>
  <dd class="rd-dd">x values at which to compute "checkpoints" of the subjectss growth trajectory to compare to other subjects</dd>
  <dt>z_bins</dt>
  <dd class="rd-dd">a vector indicating binning of z-scores for the subjects trajectory at each checkpoint with respect to the the WHO growth standard</dd>
  <dt>x_trans, y_trans</dt>
  <dd class="rd-dd">transformation functions to be applied to x and y prior to modeling</dd>
  <dt>x_inv, y_inv</dt>
  <dd class="rd-dd">inverse transformation functions for x and y to get back to the original scale after modeling</dd>
  <dt>...</dt>
  <dd class="rd-dd">parameters passed on to the fitting method</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>fit <- fit_trajectory(subset(cpp, subjid == 2), y_var = "wtkg", method = "rlm")
plot(fit$xy$x, fit$xy$y)
lines(fit$fitgrid$x, fit$fitgrid$y)
# there is also a plot method:
plot(fit, x_range = c(0, 2560))
# we can fit the z-scores instead
fit2 <- fit_trajectory(subset(cpp, subjid == 2), y_var = "waz", method = "rlm")
plot(fit2$xy$x, fit2$xy$z)
lines(fit2$fitgrid$x, fit2$fitgrid$z)</code></pre>



## fit_all_trajectories

<h3>Apply trajectory fitting to each subject in a data set</h3>


<h4>Usage</h4>
<pre class="r"><code>fit_all_trajectories(dat, subjid = "subjid", x_var = "agedays",
  y_var = "htcm", method = "gam", checkpoints = 365 * c(1:2),
  z_bins = c(-2, 2), x_trans = NULL, x_inv = NULL, y_trans = NULL,
  y_inv = NULL)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">a data frame containing data for several subjects or a ddf already divided by subject, as obtained from <code><a href=#by_subject>by_subject</a></code></dd>
  <dt>subjid</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains the subjects identifier</dd>
  <dt>x_var</dt>
  <dd class="rd-dd">name of x variable to model</dd>
  <dt>y_var</dt>
  <dd class="rd-dd">name of y variable to model</dd>
  <dt>method</dt>
  <dd class="rd-dd">one of "gam", "loess", "fda", "rlm"</dd>
  <dt>checkpoints</dt>
  <dd class="rd-dd">x values at which to compute "checkpoints" of the subjectss growth trajectory to compare to other subjects</dd>
  <dt>z_bins</dt>
  <dd class="rd-dd">a vector indicating binning of z-scores for the subjects trajectory at each checkpoint with respect to the the WHO growth standard</dd>
  <dt>x_trans, y_trans</dt>
  <dd class="rd-dd">transformation functions to be applied to x and y prior to modeling</dd>
  <dt>x_inv, y_inv</dt>
  <dd class="rd-dd">inverse transformation functions for x and y to get back to the original scale after modeling</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>cppt <- fit_all_trajectories(cpp, y_var = "wtkg", method = "rlm")
cppt[[1]]
plot(cppt[[1]]$value)</code></pre>



## plot.fittedTrajectory

<h3>Plot a fitted trajectory</h3>


<h4>Usage</h4>
<pre class="r"><code>plotfittedTrajectory(x, center = FALSE, x_range = NULL,
  width = 500, height = 520, hover = NULL, checkpoints = TRUE, p = 100
  * pnorm(-3:0), ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">an object returned from <code><a href=#fit_trajectory>fit_trajectory</a></code></dd>
  <dt>center</dt>
  <dd class="rd-dd">should the trajectory be centered around the median WHO standard?  This is equivalent to plotting the age difference score (like height-for-age difference - HAD)</dd>
  <dt>x_range</dt>
  <dd class="rd-dd">a vector specifying the range (min, max) that the superposed growth standard should span on the x-axis</dd>
  <dt>width</dt>
  <dd class="rd-dd">width of the plot</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of the plot</dd>
  <dt>hover</dt>
  <dd class="rd-dd">variable names in <code>x$data</code> to show on hover for each point (only variables with non-NA data will be shown)</dd>
  <dt>checkpoints</dt>
  <dd class="rd-dd">should the checkpoints be plotted (if available)?</dd>
  <dt>p</dt>
  <dd class="rd-dd">centiles at which to draw the WHO polygons</dd>
  <dt>...</dt>
  <dd class="rd-dd">additional parameters passed to <code><a href=http://www.inside-r.org/packages/cran/rbokeh/docs/figure>figure</a></code></dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>fit <- fit_trajectory(subset(cpp, subjid == 2), y_var = "wtkg", method = "rlm")
plot(fit)
plot(fit, center = TRUE)
plot(fit, hover = c("wtkg", "bmi", "waz", "haz"))</code></pre>



## plot_z

<h3>Plot a fitted trajectory on z-score scale</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_z(x, x_range = NULL, width = 500, height = 520, hover = NULL,
  checkpoints = TRUE, z = -3:0, ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">an object returned from <code><a href=#fit_trajectory>fit_trajectory</a></code></dd>
  <dt>x_range</dt>
  <dd class="rd-dd">a vector specifying the range (min, max) that the superposed z-score bands should span on the x-axis</dd>
  <dt>width</dt>
  <dd class="rd-dd">width of the plot</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of the plot</dd>
  <dt>hover</dt>
  <dd class="rd-dd">variable names in <code>x$data</code> to show on hover for each point (only variables with non-NA data will be shown)</dd>
  <dt>checkpoints</dt>
  <dd class="rd-dd">should the checkpoints be plotted (if available)?</dd>
  <dt>z</dt>
  <dd class="rd-dd">z-scores at which to draw the z-score bands</dd>
  <dt>...</dt>
  <dd class="rd-dd">additional parameters passed to <code><a href=http://www.inside-r.org/packages/cran/rbokeh/docs/figure>figure</a></code></dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>fit <- fit_trajectory(subset(cpp, subjid == 2), y_var = "wtkg", method = "rlm")
plot_z(fit)</code></pre>



## plot_velocity

<h3>Plot a fitted trajectory's velocity</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_velocity(x, width = 500, height = 520, ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">an object returned from <code><a href=#fit_trajectory>fit_trajectory</a></code></dd>
  <dt>width</dt>
  <dd class="rd-dd">width of the plot</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of the plot</dd>
  <dt>...</dt>
  <dd class="rd-dd">additional parameters passed to <code><a href=http://www.inside-r.org/packages/cran/rbokeh/docs/figure>figure</a></code></dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>fit <- fit_trajectory(subset(cpp, subjid == 2), y_var = "wtkg", method = "rlm")
plot_velocity(fit)</code></pre>



## plot_zvelocity

<h3>Plot a fitted trajectory's z-score velocity</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_zvelocity(x, width = 500, height = 520, ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">an object returned from <code><a href=#fit_trajectory>fit_trajectory</a></code></dd>
  <dt>width</dt>
  <dd class="rd-dd">width of the plot</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of the plot</dd>
  <dt>...</dt>
  <dd class="rd-dd">additional parameters passed to <code><a href=http://www.inside-r.org/packages/cran/rbokeh/docs/figure>figure</a></code></dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>fit <- fit_trajectory(subset(cpp, subjid == 2), y_var = "wtkg", method = "rlm")
plot_zvelocity(fit)</code></pre>



## fit_method.gam

<h3>Compute spline fit of growth trajectory</h3>


<h4>Usage</h4>
<pre class="r"><code>fit_methodgam(dat, xg = NULL, cpx = NULL, ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data frame specifying x and y coordinates of data to fit</dd>
  <dt>xg</dt>
  <dd class="rd-dd">x grid across which to compute fits for plotting (default is sequence along the range of <code>x</code>)</dd>
  <dt>cpx</dt>
  <dd class="rd-dd">x values at which to compute "checkpoints" of the fitted subjectss growth trajectory to compare to other subjects</dd>
  <dt>...</dt>
  <dd class="rd-dd">additional parameters passed to <code><a href=http://www.inside-r.org/r-doc/mgcv/gam>gam</a></code></dd>
</dl>

  <h4>Note</h4>

  <p class="rd-p">The trajectory fitting functions are most easily accessed through calling <code><a href=#fit_trajectory>fit_trajectory</a></code> with the <code>method</code> argument to specify the modeling approach to use.</p>

  <p class="rd-p">These fitting functions can easily be replaced by simply calling the associated R methods, but are provided for convenience to standardize input/output to simplify swapping fitting methods.</p>






## fit_method.loess

<h3>Compute loess fit of growth trajectory</h3>


<h4>Usage</h4>
<pre class="r"><code>fit_methodloess(dat, xg = NULL, cpx = NULL, span = c(0.05, 3),
  degree = c(1, 2), family = "symmetric", ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data frame specifying x and y coordinates of data to fit</dd>
  <dt>xg</dt>
  <dd class="rd-dd">x grid across which to compute fits for plotting (default is sequence along the range of <code>x</code>)</dd>
  <dt>cpx</dt>
  <dd class="rd-dd">x values at which to compute "checkpoints" of the fitted subjectss growth trajectory to compare to other subjects</dd>
  <dt>span</dt>
  <dd class="rd-dd"><code><a href=http://www.inside-r.org/r-doc/stats/loess>loess</a></code> smoothing parameter</dd>
  <dt>degree</dt>
  <dd class="rd-dd"><code><a href=http://www.inside-r.org/r-doc/stats/loess>loess</a></code> smoothing parameter</dd>
  <dt>family</dt>
  <dd class="rd-dd"><code><a href=http://www.inside-r.org/r-doc/stats/loess>loess</a></code> smoothing parameter</dd>
  <dt>...</dt>
  <dd class="rd-dd">additional parameters passed to <code><a href=http://www.inside-r.org/r-doc/stats/loess>loess</a></code></dd>
</dl>

  <h4>Note</h4>

  <p class="rd-p">The trajectory fitting functions are most easily accessed through calling <code><a href=#fit_trajectory>fit_trajectory</a></code> with the <code>method</code> argument to specify the modeling approach to use.</p>

  <p class="rd-p">These fitting functions can easily be replaced by simply calling the associated R methods, but are provided for convenience to standardize input/output to simplify swapping fitting methods.</p>






## fit_method.rlm

<h3>Compute robust linear model fit of growth trajectory</h3>


<h4>Usage</h4>
<pre class="r"><code>fit_methodrlm(dat, xg = NULL, cpx = NULL, p = 2, ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data frame specifying x and y coordinates of data to fit</dd>
  <dt>xg</dt>
  <dd class="rd-dd">x grid across which to compute fits for plotting (default is sequence along the range of <code>x</code>)</dd>
  <dt>cpx</dt>
  <dd class="rd-dd">x values at which to compute "checkpoints" of the fitted subjectss growth trajectory to compare to other subjects</dd>
  <dt>p</dt>
  <dd class="rd-dd">order of polynomial fit (default is quadratic, p=2)</dd>
  <dt>...</dt>
  <dd class="rd-dd">additional parameters passed to <code><a href=http://www.inside-r.org/r-doc/MASS/rlm>rlm</a></code></dd>
</dl>

  <h4>Note</h4>

  <p class="rd-p">The trajectory fitting functions are most easily accessed through calling <code><a href=#fit_trajectory>fit_trajectory</a></code> with the <code>method</code> argument to specify the modeling approach to use.</p>

  <p class="rd-p">These fitting functions can easily be replaced by simply calling the associated R methods, but are provided for convenience to standardize input/output to simplify swapping fitting methods.</p>






## auto_loess

<h3>Find best loess fit based on aic or gcv</h3>


<h4>Usage</h4>
<pre class="r"><code>auto_loess(data, span = c(0.01, 2), degree = c(1, 2), family = "gaussian",
  which = "gcv", ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>data</dt>
  <dd class="rd-dd">a data frame with columns x and y to be used in the fitting</dd>
  <dt>span</dt>
  <dd class="rd-dd">a vector indicating a range (min, max) of spans to search over</dd>
  <dt>degree</dt>
  <dd class="rd-dd">a vector of degrees to search over (valid values are combinations of 0, 1, 2)</dd>
  <dt>family</dt>
  <dd class="rd-dd">loess <code>family</code> parameter</dd>
  <dt>which</dt>
  <dd class="rd-dd">which method to use, "aicc" or "gcv"</dd>
  <dt>...</dt>
  <dd class="rd-dd">additional parameters passed to <code><a href=http://www.inside-r.org/r-doc/stats/loess>loess</a></code></dd>
</dl>



# Summary Vis



## plot_univar

<h3>Make a grid of univariate summary plots</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_univar(dat, subject = FALSE, ncol = 3, width = 300, height = 300)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data frame</dd>
  <dt>subject</dt>
  <dd class="rd-dd">should subject-level (TRUE) or time-varying (FALSE) variables be plotted?</dd>
  <dt>ncol</dt>
  <dd class="rd-dd">number of columns in the grid</dd>
  <dt>width</dt>
  <dd class="rd-dd">width of each plot in pixels</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of each plot in pixels</dd>
</dl>

  <h4>Details</h4>

  <p class="rd-p">Subject-level variables are treated differently than time-varying variables in that they are repeated for each subject.  When plotting summaries of subject-level variables, the data is first subset to one record per subject.</p>



<h4>Examples</h4>
<pre class="r"><code>plot_univar(cpp, subject = TRUE)
plot_univar(cpp)</code></pre>



## plot_missing

<h3>Plot a stacked bar chart indicating NAs for each variable in a data set</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_missing(dat, subject = FALSE, width = 800, height = 500, ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data frame</dd>
  <dt>subject</dt>
  <dd class="rd-dd">should subject-level (TRUE) or time-varying (FALSE) variables be plotted?</dd>
  <dt>width</dt>
  <dd class="rd-dd">width of plot in pixels</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of plot in pixels</dd>
  <dt>...</dt>
  <dd class="rd-dd">additional parameters passed to <code><a href=http://www.inside-r.org/packages/cran/rbokeh/docs/figure>figure</a></code></dd>
</dl>

  <h4>Details</h4>

  <p class="rd-p">Subject-level variables are treated differently than time-varying variables in that they are repeated for each subject.  When plotting summaries of subject-level variables, the data is first subset to one record per subject.</p>



<h4>Examples</h4>
<pre class="r"><code>plot_missing(cpp)
plot_missing(cpp, subject = TRUE)</code></pre>



## plot_complete_pairs

<h3>Plot a heat map of frequency of "complete" (both non-NA) pairs of variables</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_complete_pairs(dat, subject = FALSE, width = 700, height = 700,
  thresh = 0.95, ...)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data frame</dd>
  <dt>subject</dt>
  <dd class="rd-dd">should subject-level (TRUE) or time-varying (FALSE) variables be plotted?</dd>
  <dt>width</dt>
  <dd class="rd-dd">width of plot in pixels</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of plot in pixels</dd>
  <dt>thresh</dt>
  <dd class="rd-dd">percentage NA threshold above which variables will be ignored (to help deal with cases involving many variables)</dd>
  <dt>...</dt>
  <dd class="rd-dd">additional parameters passed to <code><a href=http://www.inside-r.org/packages/cran/rbokeh/docs/figure>figure</a></code></dd>
</dl>

  <h4>Details</h4>

  <p class="rd-p">Subject-level variables are treated differently than time-varying variables in that they are repeated for each subject.  When plotting summaries of subject-level variables, the data is first subset to one record per subject.</p>



<h4>Examples</h4>
<pre class="r"><code>plot_complete_pairs(cpp)
plot_complete_pairs(cpp, subject = TRUE)</code></pre>



## plot_agefreq

<h3>Plot age frequency</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_agefreq(agefreq, xlab = "Age since birth at examination (days)",
  ylab = "# examinations", width = 700, height = 350)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>agefreq</dt>
  <dd class="rd-dd">an object returned from <code><a href=#get_agefreq>get_agefreq</a></code></dd>
  <dt>xlab</dt>
  <dd class="rd-dd">label for x axis</dd>
  <dt>ylab</dt>
  <dd class="rd-dd">label for y axis</dd>
  <dt>width</dt>
  <dd class="rd-dd">width of plot in pixels</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of plot in pixels</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>agefreq <- get_agefreq(cpp)
plot_agefreq(agefreq)</code></pre>



## plot_first_visit_age

<h3>Plot histogram and quantile plot of age at first visit</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_first_visit_age(dat, subjid = "subjid", agevar = "agedays",
  agelab = "first visit age (days)", width = 450, height = 450)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">a longitudinal growth study data set</dd>
  <dt>subjid</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains the subjects identifier</dd>
  <dt>agevar</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains a measure of the subjects age</dd>
  <dt>agelab</dt>
  <dd class="rd-dd">label of the age axis</dd>
  <dt>width</dt>
  <dd class="rd-dd">the width of each plot in pixels</dd>
  <dt>height</dt>
  <dd class="rd-dd">the height of each plot in pixels</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>plot_first_visit_age(cpp)</code></pre>



## plot_visit_distn

<h3>Plot histogram and quantile plot of number of "visits" for each subject</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_visit_distn(dat, subjid = "subjid", width = 450, height = 450)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">a longitudinal growth study data set</dd>
  <dt>subjid</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains the subjects identifier</dd>
  <dt>width</dt>
  <dd class="rd-dd">the width of each plot in pixels</dd>
  <dt>height</dt>
  <dd class="rd-dd">the height of each plot in pixels</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>plot_visit_distn(cpp)</code></pre>

# Multi-Study Vis



## plot_var_matrix

<h3>Plot a matrix comparing variables present in a list of studies</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_var_matrix(dat_list, width = 845, h_padding = 0, subjid = "subjid",
  agevar = "agedays")</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat_list</dt>
  <dd class="rd-dd">a list of data frames containing study data</dd>
  <dt>width</dt>
  <dd class="rd-dd">width of the plot in pixels</dd>
  <dt>h_padding</dt>
  <dd class="rd-dd">extra height to add to the plot to account for long variable names</dd>
  <dt>subjid</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains the subjects identifier</dd>
  <dt>agevar</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains a measure of the subjects age</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>dat_list <- list(
  cpp1 = cpp[,c(1:5, 7:9, 14:19, 23:32)],
  cpp2 = cpp[,c(1:5, 11:24)],
  cpp3 = cpp
)
plot_var_matrix(dat_list)</code></pre>



## plot_multi_subj_boxplot

<h3>Plot boxplots of distrubutions of number of records per subject for a list of studies</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_multi_subj_boxplot(dat_list, subjid = "subjid", width = 800,
  height = 500)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat_list</dt>
  <dd class="rd-dd">a list of data frames containing study data</dd>
  <dt>subjid</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains the subjects identifier</dd>
  <dt>width</dt>
  <dd class="rd-dd">width of the plot in pixels</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of the plot in pixels</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>dat_list <- list(
  cpp1 = cpp,
  cpp2 = cpp,
  cpp3 = cpp
)
plot_multi_subj_boxplot(dat_list)</code></pre>



## plot_time_count_grid

<h3>Plot counts by age for a list of studies</h3>


<h4>Usage</h4>
<pre class="r"><code>plot_time_count_grid(dat_list, agevar = "agedays",
  xlab = "Age since birth at examination (days)", width = 845,
  height = 80)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat_list</dt>
  <dd class="rd-dd">a list of data frames containing study data</dd>
  <dt>agevar</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains a measure of the subjects age</dd>
  <dt>xlab</dt>
  <dd class="rd-dd">label for x axis</dd>
  <dt>width</dt>
  <dd class="rd-dd">width of the plot in pixels</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of each panel of the plot in pixels</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>dat_list <- list(
  cpp1 = cpp,
  cpp2 = cpp,
  cpp3 = cpp
)
plot_time_count_grid(dat_list)</code></pre>

# Trelliscope Vis



## trscope_trajectories

<h3>Create Trelliscope display of subject trajectories</h3>


<h4>Usage</h4>
<pre class="r"><code>trscope_trajectories(dat, center = FALSE, who_range = NULL, width = 500,
  height = 520, name = NULL, desc = "", group = NULL,
  vdbConn = getOption("vdbConn"), view = TRUE)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">either a data frame or object created by <code><a href=#by_subject>by_subject</a></code> or <code><a href=#fit_all_trajectories>fit_all_trajectories</a></code></dd>
  <dt>center</dt>
  <dd class="rd-dd">should the trajectory be centered around the median WHO standard?</dd>
  <dt>who_range</dt>
  <dd class="rd-dd">a vector specifying the range (min, max) that the superposed WHO growth standard should span on the x-axis</dd>
  <dt>width</dt>
  <dd class="rd-dd">width of the plot</dd>
  <dt>height</dt>
  <dd class="rd-dd">height of the plot</dd>
  <dt>name</dt>
  <dd class="rd-dd">name of the Trelliscope display (if left NULL, will be implied by the vairables being plotted)</dd>
  <dt>desc</dt>
  <dd class="rd-dd">description of the Trelliscope display</dd>
  <dt>group</dt>
  <dd class="rd-dd">group in which to place the Trelliscope display</dd>
  <dt>vdbConn</dt>
  <dd class="rd-dd">an optional VDB connection</dd>
  <dt>view</dt>
  <dd class="rd-dd">should the plot be viewed upon creation?</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>  cppsubj <- by_subject(cpp)
  cppt <- fit_all_trajectories(cppsubj, method = "rlm")
  cppt <- trscope_trajectories(cppt)</code></pre>

# Divisions



## by_subject

<h3>Divide a data set into subsets by subject</h3>


<h4>Usage</h4>
<pre class="r"><code>by_subject(dat, subjid = "subjid")</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data set to divide by subject</dd>
  <dt>subjid</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains the subjects identifier</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>cppsubj <- by_subject(cpp)</code></pre>



## by_trajectory_checkpoints

<h3>Split by-subject trajectory-fitted data by checkpoint categorizations</h3>


<h4>Usage</h4>
<pre class="r"><code>by_trajectory_checkpoints(dat, complete = TRUE)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">a data object returned by <code><a href=#fit_all_trajectories>fit_all_trajectories</a></code></dd>
  <dt>complete</dt>
  <dd class="rd-dd">subset only to those that have fitted checkpoints</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>cppsubj <- by_subject(cpp)
cppt <- fit_all_trajectories(cppsubj, method = "rlm")
cppcp <- by_trajectory_checkpoints(cppt)</code></pre>

# Data Sets



## cpp

<h3>Subset of growth data from the collaborative perinatal project (CPP)</h3>

<p class="rd-p">Subset of growth data from the collaborative perinatal project (CPP).</p>

<h4>Usage</h4>
<pre class="r"><code>cpp</code></pre>

  <h4>Source</h4>

  <p class="rd-p"><a href = https://catalog.archives.gov/id/606622>https://catalog.archives.gov/id/606622</a></p>

  <p class="rd-p">Broman, Sarah. "The collaborative perinatal project: an overview." Handbook of longitudinal research 1 (1984): 185-227.</p>



<h4>Examples</h4>
<pre class="r"><code>head(cpp)</code></pre>



## who_coefs

<h3>List of WHO growth standard coefficients</h3>

<p class="rd-p">A list of coefficients from the WHO for various pairs of growth standards that are used to compute quantiles and z-scores.  The format is a list, where each element is a pairing of variables, e.g. "wtkg_agedays", "htcm_agedays", "bmi_agedays", "hcircm_agedays", "muaccm_agedays", "ss_agedays", "tsftmm_agedays", "wtkg_lencm""wtkg_htcm".  Within each of these elements is a list for sex with names "Female" and "Male".</p>

  <h4>Source</h4>

  <p class="rd-p">0-5 years: <a href = http://www.who.int/childgrowth/software/en/>http://www.who.int/childgrowth/software/en/</a></p>

  <p class="rd-p">5-15 years: <a href = http://www.who.int/growthref/tools/en/>http://www.who.int/growthref/tools/en/</a></p>



<h4>Examples</h4>
<pre class="r"><code>head(who_coefs$htcm_age$Female$data)</code></pre>

<h4>See also</h4>

<code><a href=#who_centile2value>who_centile2value</a></code>, <code><a href=#who_value2zscore>who_value2centile</a></code>, <code><a href=#who_centile2value>who_zscore2value</a></code>, <code><a href=#who_value2zscore>who_value2zscore</a></code>




## ig_coefs

<h3>List of Intergrowth birth standard coefficients</h3>

<p class="rd-p">A list of coefficients from the Integrowth birth standard.</p>

  <h4>Source</h4>

  <p class="rd-p"><a href = https://intergrowth21.tghn.org>https://intergrowth21.tghn.org</a></p>


  <h4>References</h4>

  <p class="rd-p">International standards for newborn weight, length, and head circumference by gestational age and sex: the Newborn Cross-Sectional Study of the INTERGROWTH-21st Project
Villar, José et al.
The Lancet, Volume 384, Issue 9946, 857-868</p>



<h4>Examples</h4>
<pre class="r"><code>head(ig_coefs$hcircm$Female)</code></pre>

<h4>See also</h4>

<code><a href=#igb_zscore2value>igb_centile2value</a></code>, <code><a href=#igb_value2zscore>igb_value2centile</a></code>, <code><a href=#igb_zscore2value>igb_zscore2value</a></code>, <code><a href=#igb_value2zscore>igb_value2zscore</a></code>




## hbgd_labels

<h3>Labels for common variable names in hbgd data</h3>

<p class="rd-p">Labels for common variable names in hbgd data, used in <code><a href='get_data_attributes.html'>get_data_attributes</a></code> if labels are not explicitly provided.</p>

<h4>Usage</h4>
<pre class="r"><code>hbgd_labels</code></pre>



<h4>See also</h4>

<code><a href=#get_data_attributes>get_data_attributes</a></code>




## hbgd_labels_df

<h3>Labels for common variable names in hbgd data</h3>

<p class="rd-p">Labels for common variable names in hbgd data, used in <code><a href='get_data_attributes.html'>get_data_attributes</a></code> if labels are not explicitly provided.</p>

<h4>Usage</h4>
<pre class="r"><code>hbgd_labels_df</code></pre>



# Misc



## get_subject_data

<h3>Get subject-level or time-varying variables and rows of longitudinal data</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data frame with longitudinal data</dd>
</dl>





## get_time_data

<h3>Get subject-level or time-varying variables and rows of longitudinal data</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data frame with longitudinal data</dd>
</dl>





## get_data_attributes

<h3>Infer and attach attributes to a longitudinal growth study data set</h3>

<p class="rd-p">Infer attributes such as variable types of a longitudinal growth study and add as attributes to the data set.</p>

<h4>Usage</h4>
<pre class="r"><code>get_data_attributes(dat, subjid = "subjid", agevars = "agedays",
  meta = NULL, study_meta = NULL)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">a longitudinal growth study data set</dd>
  <dt>subjid</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains the subjects identifier</dd>
  <dt>agevars</dt>
  <dd class="rd-dd">variable name (or vector of names) that indicates a measure (or measures) of the subjects age</dd>
  <dt>meta</dt>
  <dd class="rd-dd">a data frame of meta data about the variables (a row for each variable)</dd>
  <dt>study_meta</dt>
  <dd class="rd-dd">a single-row data frame or named list of meta data about the study (such as study description, etc.)</dd>
</dl>

  <h4>Details</h4>

  <p class="rd-p">attributes added:
- <code>subjectlevel_vars</code>: vector of names of subject-level variables
- <code>timevarying_vars</code>: vector of names of time-varying variables
- <code>time_vars</code>: vector of names of measures of age
- <code>var_summ</code>: data frame containing variable summaries with columns <code>variable</code>, <code>label</code>, <code>type</code>[subject id, time indicator, time-varying, constant], <code>n_unique</code>
- <code>subj_count</code>: data frame of counts of records for each subject with columns <code>subjid</code>, <code>n</code>
- <code>n_subj</code>: scalar containing total number of subjects
- <code>labels</code> named list of variable labels - either populated by matching names with a pre-set list of labels (see <code><a href=#hbgd_labels>hbgd_labels</a></code>) or from a list provided from the <code>meta</code> argument
- <code>study_meta</code>: data frame of meta data (if provided from the <code>study_meta</code> argument)
- <code>short_id</code>: scalar containing the short unique identifier for the study (if <code>study_meta</code> is provided)</p>



<h4>Examples</h4>
<pre class="r"><code>cpp <- get_data_attributes(cpp)
str(attributes(cpp))</code></pre>

<h4>See also</h4>

<code><a href=#get_data_attributes>get_data_attributes</a></code>




## fix_height

<h3>Merge htcm and lencm into one variable</h3>


<h4>Usage</h4>
<pre class="r"><code>fix_height(dat, height_var = "htcm", length_var = "lencm",
  target = "htcm")</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">data</dd>
  <dt>height_var</dt>
  <dd class="rd-dd">name of height variable</dd>
  <dt>length_var</dt>
  <dd class="rd-dd">name of length variable</dd>
  <dt>target</dt>
  <dd class="rd-dd">name of target variable to hold the merged variable</dd>
</dl>





## grid_deriv

<h3>Estimate derivative given a grid of points</h3>


<h4>Usage</h4>
<pre class="r"><code>grid_deriv(x, y)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">x variable (should be a regularly-spaced grid of points)</dd>
  <dt>y</dt>
  <dd class="rd-dd">y variable</dd>
</dl>





## get_agefreq

<h3>Get age frequency</h3>


<h4>Usage</h4>
<pre class="r"><code>get_agefreq(dat, agevar = "agedays", age_range = NULL)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>dat</dt>
  <dd class="rd-dd">a longitudinal growth study data set</dd>
  <dt>agevar</dt>
  <dd class="rd-dd">variable name in <code>dat</code> that contains a measure of the subjects age</dd>
  <dt>age_range</dt>
  <dd class="rd-dd">optional range to ....</dd>
</dl>


<h4>Examples</h4>
<pre class="r"><code>agefreq <- get_agefreq(cpp)
plot_agefreq(agefreq)</code></pre>



## log10_1

<h3>log base 10 plus 1</h3>


<h4>Usage</h4>
<pre class="r"><code>log10_1(x)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">vector of data</dd>
</dl>





## exp10_1

<h3>Inverse of log base 10 plus 1</h3>


<h4>Usage</h4>
<pre class="r"><code>exp10_1(x)</code></pre>

<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">vector of data</dd>
</dl>



# Unit Conversion



## cm2in

<h3>Unit conversion utility functions</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value(s) to convert</dd>
</dl>





## in2cm

<h3>Unit conversion utility functions</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value(s) to convert</dd>
</dl>





## lb2kg

<h3>Unit conversion utility functions</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value(s) to convert</dd>
</dl>





## kg2lb

<h3>Unit conversion utility functions</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value(s) to convert</dd>
</dl>





## days2years

<h3>Unit conversion utility functions</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value(s) to convert</dd>
</dl>





## years2days

<h3>Unit conversion utility functions</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value(s) to convert</dd>
</dl>





## days2months

<h3>Unit conversion utility functions</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value(s) to convert</dd>
</dl>





## months2days

<h3>Unit conversion utility functions</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value(s) to convert</dd>
</dl>





## months2years

<h3>Unit conversion utility functions</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value(s) to convert</dd>
</dl>





## years2months

<h3>Unit conversion utility functions</h3>


<h4>Arguments</h4>
<dl class="rd-dl">
  <dt>x</dt>
  <dd class="rd-dd">value(s) to convert</dd>
</dl>




